# Generated by Django 4.2 on 2023-06-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_connexion', models.CharField(max_length=60, unique=True, verbose_name='Le lien de connexion')),
                ('statut_lien', models.IntegerField(default=0, verbose_name='Le statut du lien')),
                ('role_lien', models.CharField(choices=[('CHEF', 'Chef de groupe'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=10, verbose_name="Le role que va avoir l'employé")),
                ('poste_lien', models.CharField(max_length=50, verbose_name='Post employé')),
                ('date_creation', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lienconnexion', to=settings.AUTH_USER_MODEL, verbose_name="L'employé inscrit")),
            ],
        ),
    ]
